// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4586248237007907258),
    name: 'Project',
    lastPropertyId: const obx_int.IdUid(2, 4565180862407038464),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5338282227961137775),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4565180862407038464),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(name: 'tasks', srcEntity: 'Task', srcField: ''),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2166071371638146430),
    name: 'Task',
    lastPropertyId: const obx_int.IdUid(6, 6463368824846576933),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5438403364332432677),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4691259114376190203),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6786321433711601981),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7375566084544407708),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2705602480657851208),
        name: 'priority',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6463368824846576933),
        name: 'projectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3959085063464020899),
        relationTarget: 'Project',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 2166071371638146430),
    lastIndexId: const obx_int.IdUid(1, 3959085063464020899),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Project: obx_int.EntityDefinition<Project>(
      model: _entities[0],
      toOneRelations: (Project object) => [],
      toManyRelations: (Project object) => {
        obx_int.RelInfo<Task>.toOneBacklink(
          6,
          object.id,
          (Task srcObject) => srcObject.project,
        ): object.tasks,
      },
      getId: (Project object) => object.id,
      setId: (Project object, int id) {
        object.id = id;
      },
      objectToFB: (Project object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Project(id: idParam, name: nameParam);
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.tasks,
          store,
          obx_int.RelInfo<Task>.toOneBacklink(
            6,
            object.id,
            (Task srcObject) => srcObject.project,
          ),
        );
        return object;
      },
    ),
    Task: obx_int.EntityDefinition<Task>(
      model: _entities[1],
      toOneRelations: (Task object) => [object.project],
      toManyRelations: (Task object) => {},
      getId: (Task object) => object.id,
      setId: (Task object, int id) {
        object.id = id;
      },
      objectToFB: (Task object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final priorityOffset = fbb.writeString(object.priority);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.isCompleted);
        fbb.addOffset(4, priorityOffset);
        fbb.addInt64(5, object.project.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final priorityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Task(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          isCompleted: isCompletedParam,
          priority: priorityParam,
        );
        object.project.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.project.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Project] entity fields to define ObjectBox queries.
class Project_ {
  /// See [Project.id].
  static final id = obx.QueryIntegerProperty<Project>(
    _entities[0].properties[0],
  );

  /// See [Project.name].
  static final name = obx.QueryStringProperty<Project>(
    _entities[0].properties[1],
  );

  /// see [Project.tasks]
  static final tasks = obx.QueryBacklinkToMany<Task, Project>(Task_.project);
}

/// [Task] entity fields to define ObjectBox queries.
class Task_ {
  /// See [Task.id].
  static final id = obx.QueryIntegerProperty<Task>(_entities[1].properties[0]);

  /// See [Task.title].
  static final title = obx.QueryStringProperty<Task>(
    _entities[1].properties[1],
  );

  /// See [Task.description].
  static final description = obx.QueryStringProperty<Task>(
    _entities[1].properties[2],
  );

  /// See [Task.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Task>(
    _entities[1].properties[3],
  );

  /// See [Task.priority].
  static final priority = obx.QueryStringProperty<Task>(
    _entities[1].properties[4],
  );

  /// See [Task.project].
  static final project = obx.QueryRelationToOne<Task, Project>(
    _entities[1].properties[5],
  );
}
