// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5987755979586042326),
    name: 'Cases',
    lastPropertyId: const obx_int.IdUid(9, 1788708145798285448),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 873669746042240539),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1117723866432946971),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2188002583798074303),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5427535127017679226),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2793956897749736983),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2920017413183951074),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 835383754916880870),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7597687946002918499),
        name: 'syncStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1788708145798285448),
        name: 'siteId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1141804172224828895),
        relationTarget: 'Site',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(name: 'tasks', srcEntity: 'Task', srcField: ''),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4103364348808290971),
    name: 'Site',
    lastPropertyId: const obx_int.IdUid(6, 881195963482113616),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1926738073892208001),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2965954837752612982),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2266942386657407149),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5293453927097003824),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6504701300730260958),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 881195963482113616),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(name: 'cases', srcEntity: 'Cases', srcField: ''),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6951854009226048597),
    name: 'Task',
    lastPropertyId: const obx_int.IdUid(10, 1510236068449065997),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1704086620076641886),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8900095076106591150),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2262335127534580950),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7440924538538997225),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 47120247087423895),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5352919661346108499),
        name: 'priority',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4780525010590642687),
        name: 'reviewNotes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3664418709527248735),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3824721670207459438),
        name: 'updatedBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1510236068449065997),
        name: 'casesId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4766741117893378971),
        relationTarget: 'Cases',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'images',
        srcEntity: 'TaskImage',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1090666384585365990),
    name: 'TaskImage',
    lastPropertyId: const obx_int.IdUid(4, 9077922077441743378),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3104296346293559759),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2869600950031884541),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7721192077191812636),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9077922077441743378),
        name: 'taskId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 835504123421426432),
        relationTarget: 'Task',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 712994506514691974),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(3, 2097911737486883927),
    flags: 2,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2090712227813124997),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2113646510057666482),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2097911737486883927),
        name: 'password',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 712994506514691974),
    lastIndexId: const obx_int.IdUid(3, 835504123421426432),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Cases: obx_int.EntityDefinition<Cases>(
      model: _entities[0],
      toOneRelations: (Cases object) => [object.site],
      toManyRelations: (Cases object) => {
        obx_int.RelInfo<Task>.toOneBacklink(
          10,
          object.id,
          (Task srcObject) => srcObject.cases,
        ): object.tasks,
      },
      getId: (Cases object) => object.id,
      setId: (Cases object, int id) {
        object.id = id;
      },
      objectToFB: (Cases object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final syncStatusOffset = fbb.writeString(object.syncStatus);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isSynced);
        fbb.addInt64(6, object.lastSyncedAt?.millisecondsSinceEpoch);
        fbb.addOffset(7, syncStatusOffset);
        fbb.addInt64(8, object.site.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastSyncedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final lastSyncedAtParam = lastSyncedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastSyncedAtValue);
        final syncStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = Cases(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          lastSyncedAt: lastSyncedAtParam,
          syncStatus: syncStatusParam,
        );
        object.site.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.site.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Cases>(
          object.tasks,
          store,
          obx_int.RelInfo<Task>.toOneBacklink(
            10,
            object.id,
            (Task srcObject) => srcObject.cases,
          ),
        );
        return object;
      },
    ),
    Site: obx_int.EntityDefinition<Site>(
      model: _entities[1],
      toOneRelations: (Site object) => [],
      toManyRelations: (Site object) => {
        obx_int.RelInfo<Cases>.toOneBacklink(
          9,
          object.id,
          (Cases srcObject) => srcObject.site,
        ): object.cases,
      },
      getId: (Site object) => object.id,
      setId: (Site object, int id) {
        object.id = id;
      },
      objectToFB: (Site object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = Site(
          id: idParam,
          name: nameParam,
          address: addressParam,
          description: descriptionParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<Site>(
          object.cases,
          store,
          obx_int.RelInfo<Cases>.toOneBacklink(
            9,
            object.id,
            (Cases srcObject) => srcObject.site,
          ),
        );
        return object;
      },
    ),
    Task: obx_int.EntityDefinition<Task>(
      model: _entities[2],
      toOneRelations: (Task object) => [object.cases],
      toManyRelations: (Task object) => {
        obx_int.RelInfo<TaskImage>.toOneBacklink(
          4,
          object.id,
          (TaskImage srcObject) => srcObject.task,
        ): object.images,
      },
      getId: (Task object) => object.id,
      setId: (Task object, int id) {
        object.id = id;
      },
      objectToFB: (Task object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final priorityOffset = fbb.writeString(object.priority);
        final reviewNotesOffset = fbb.writeString(object.reviewNotes);
        final updatedByOffset = fbb.writeString(object.updatedBy);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.isCompleted);
        fbb.addBool(4, object.isSynced);
        fbb.addOffset(5, priorityOffset);
        fbb.addOffset(6, reviewNotesOffset);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(8, updatedByOffset);
        fbb.addInt64(9, object.cases.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final priorityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final reviewNotesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = Task(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          isCompleted: isCompletedParam,
          isSynced: isSyncedParam,
          priority: priorityParam,
          reviewNotes: reviewNotesParam,
          updatedAt: updatedAtParam,
          updatedBy: updatedByParam,
        );
        object.cases.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.cases.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Task>(
          object.images,
          store,
          obx_int.RelInfo<TaskImage>.toOneBacklink(
            4,
            object.id,
            (TaskImage srcObject) => srcObject.task,
          ),
        );
        return object;
      },
    ),
    TaskImage: obx_int.EntityDefinition<TaskImage>(
      model: _entities[3],
      toOneRelations: (TaskImage object) => [object.task],
      toManyRelations: (TaskImage object) => {},
      getId: (TaskImage object) => object.id,
      setId: (TaskImage object, int id) {
        object.id = id;
      },
      objectToFB: (TaskImage object, fb.Builder fbb) {
        final imageBytesOffset = fbb.writeListInt8(object.imageBytes);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, imageBytesOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.task.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final imageBytesParam = const fb.ListReader<int>(
          fb.Int8Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 6, []);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = TaskImage(
          id: idParam,
          imageBytes: imageBytesParam,
          createdAt: createdAtParam,
        );
        object.task.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.task.attach(store);
        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[4],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final emailOffset = fbb.writeString(object.email);
        final passwordOffset = fbb.writeString(object.password);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, emailOffset);
        fbb.addOffset(2, passwordOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = User(
          id: idParam,
          email: emailParam,
          password: passwordParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Cases] entity fields to define ObjectBox queries.
class Cases_ {
  /// See [Cases.id].
  static final id = obx.QueryIntegerProperty<Cases>(_entities[0].properties[0]);

  /// See [Cases.name].
  static final name = obx.QueryStringProperty<Cases>(
    _entities[0].properties[1],
  );

  /// See [Cases.description].
  static final description = obx.QueryStringProperty<Cases>(
    _entities[0].properties[2],
  );

  /// See [Cases.createdAt].
  static final createdAt = obx.QueryDateProperty<Cases>(
    _entities[0].properties[3],
  );

  /// See [Cases.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Cases>(
    _entities[0].properties[4],
  );

  /// See [Cases.isSynced].
  static final isSynced = obx.QueryBooleanProperty<Cases>(
    _entities[0].properties[5],
  );

  /// See [Cases.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<Cases>(
    _entities[0].properties[6],
  );

  /// See [Cases.syncStatus].
  static final syncStatus = obx.QueryStringProperty<Cases>(
    _entities[0].properties[7],
  );

  /// See [Cases.site].
  static final site = obx.QueryRelationToOne<Cases, Site>(
    _entities[0].properties[8],
  );

  /// see [Cases.tasks]
  static final tasks = obx.QueryBacklinkToMany<Task, Cases>(Task_.cases);
}

/// [Site] entity fields to define ObjectBox queries.
class Site_ {
  /// See [Site.id].
  static final id = obx.QueryIntegerProperty<Site>(_entities[1].properties[0]);

  /// See [Site.name].
  static final name = obx.QueryStringProperty<Site>(_entities[1].properties[1]);

  /// See [Site.address].
  static final address = obx.QueryStringProperty<Site>(
    _entities[1].properties[2],
  );

  /// See [Site.description].
  static final description = obx.QueryStringProperty<Site>(
    _entities[1].properties[3],
  );

  /// See [Site.createdAt].
  static final createdAt = obx.QueryDateProperty<Site>(
    _entities[1].properties[4],
  );

  /// See [Site.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Site>(
    _entities[1].properties[5],
  );

  /// see [Site.cases]
  static final cases = obx.QueryBacklinkToMany<Cases, Site>(Cases_.site);
}

/// [Task] entity fields to define ObjectBox queries.
class Task_ {
  /// See [Task.id].
  static final id = obx.QueryIntegerProperty<Task>(_entities[2].properties[0]);

  /// See [Task.title].
  static final title = obx.QueryStringProperty<Task>(
    _entities[2].properties[1],
  );

  /// See [Task.description].
  static final description = obx.QueryStringProperty<Task>(
    _entities[2].properties[2],
  );

  /// See [Task.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Task>(
    _entities[2].properties[3],
  );

  /// See [Task.isSynced].
  static final isSynced = obx.QueryBooleanProperty<Task>(
    _entities[2].properties[4],
  );

  /// See [Task.priority].
  static final priority = obx.QueryStringProperty<Task>(
    _entities[2].properties[5],
  );

  /// See [Task.reviewNotes].
  static final reviewNotes = obx.QueryStringProperty<Task>(
    _entities[2].properties[6],
  );

  /// See [Task.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Task>(
    _entities[2].properties[7],
  );

  /// See [Task.updatedBy].
  static final updatedBy = obx.QueryStringProperty<Task>(
    _entities[2].properties[8],
  );

  /// See [Task.cases].
  static final cases = obx.QueryRelationToOne<Task, Cases>(
    _entities[2].properties[9],
  );

  /// see [Task.images]
  static final images = obx.QueryBacklinkToMany<TaskImage, Task>(
    TaskImage_.task,
  );
}

/// [TaskImage] entity fields to define ObjectBox queries.
class TaskImage_ {
  /// See [TaskImage.id].
  static final id = obx.QueryIntegerProperty<TaskImage>(
    _entities[3].properties[0],
  );

  /// See [TaskImage.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<TaskImage>(
    _entities[3].properties[1],
  );

  /// See [TaskImage.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskImage>(
    _entities[3].properties[2],
  );

  /// See [TaskImage.task].
  static final task = obx.QueryRelationToOne<TaskImage, Task>(
    _entities[3].properties[3],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[4].properties[0]);

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[4].properties[1],
  );

  /// See [User.password].
  static final password = obx.QueryStringProperty<User>(
    _entities[4].properties[2],
  );
}
